### ISSUE TITLE
check contiguity of shape data

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/osnap#12]
we need to ensure the integrity of the shape data included in the package to make sure the spatial weights matrices are built correctly

**Comment by knaaptime** [comment]
resolved using [this](https://quiltdata.com/package/knaaptime/census) data

**Comment by knaaptime** [comment]
the tracts for 2000 and 2010 are fine, so this is only a problem for 1990. Not sure exactly what's going on, but there are definitely too many connections in a handful of places

![image](https://user-images.githubusercontent.com/4213368/48665139-52191100-ea5e-11e8-9c45-32cf4b542728.png)

**Comment by knaaptime** [comment]
I think it's just that the 1990 lines are kinda poorly digitized

![image](https://user-images.githubusercontent.com/4213368/48665766-3c5d1900-ea69-11e8-8a84-45d09efc8011.png)

**Comment by sjsrey** [comment]
I think you are correct. There look to be sliver polygons in a few spots.

**Comment by knaaptime** [comment]
this is resolved since we moved to the 1990 cartographic files
