### ISSUE TITLE
 trying to run the python program in the different directory, but it fails

### ISSUE THREAD

**Issue by suhanmappingideas** [spatialucr/osnap#21]
I am trying to run the python program in the different directory, but it fails like below
http://173.255.192.133/~suhan/STARS/python/testsr.py
![image](https://user-images.githubusercontent.com/3735841/49050064-872c0e80-f196-11e8-90eb-d7a99da7613c.png)

The same works in the directory Serge set up: http://173.255.192.133/~suhan/cgi-bin/testsr.py

It looks like I need to change the path the python in the first line of code. But I am not sure which path that I need to enter. Any thought?

I read below:
Some of these potential problems are:

The Python script is not marked as executable. When CGI scripts are not executable most web servers will let the user download it, instead of running it and sending the output to the user. For CGI scripts to run properly on Unix-like operating systems, the +x bit needs to be set. Using chmod a+x your_script.py may solve this problem.
On a Unix-like system, The line endings in the program file must be Unix style line endings. This is important because the web server checks the first line of the script (called shebang) and tries to run the program specified there. It gets easily confused by Windows line endings (Carriage Return & Line Feed, also called CRLF), so you have to convert the file to Unix line endings (only Line Feed, LF). This can be done automatically by uploading the file via FTP in text mode instead of binary mode, but the preferred way is just telling your editor to save the files with Unix line endings. Most editors support this.
Your web server must be able to read the file, and you need to make sure the permissions are correct. On unix-like systems, the server often runs as user and group www-data, so it might be worth a try to change the file ownership, or making the file world readable by using chmod a+r your_script.py.
The web server must know that the file you’re trying to access is a CGI script. Check the configuration of your web server, as it may be configured to expect a specific file extension for CGI scripts.
On Unix-like systems, the path to the interpreter in the shebang (#!/usr/bin/env python) must be correct. This line calls /usr/bin/env to find Python, but it will fail if there is no /usr/bin/env, or if Python is not in the web server’s path. If you know where your Python is installed, you can also use that full path. The commands whereis python and type -p python could help you find where it is installed. Once you know the path, you can change the shebang accordingly: #!/usr/bin/python.
The file must not contain a BOM (Byte Order Mark). The BOM is meant for determining the byte order of UTF-16 and UTF-32 encodings, but some editors write this also into UTF-8 files. The BOM interferes with the shebang line, so be sure to tell your editor not to write the BOM.
If the web server is using mod_python, mod_python may be having problems. mod_python is able to handle CGI scripts by itself, but it can also be a source of issues.

it works on my user directory, so one other thing to check would be to see if eli can add a cgi-bin directory, put a script in there and test it.

**Comment by sjsrey** [comment]
One solution would be for you to install anaconda in your user account:
https://www.anaconda.com/download/#linux

Then change the first line in your .py files that are in cgi-bin to point to the python that is installed under anaconda in the first step. You will have permission to install additional packages via pip with that python.

**Comment by knaaptime** [comment]
this [works](http://173.255.192.133/~eknaap/cgi-bin/sutest.py) in my environment using the method serge described. 

with anaconda installed, the `#!/usr/bin/env python` should find the anaconda python
