### ISSUE TITLE
move quilt data to spatialucr account

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/osnap#28]

**Comment by sjsrey** [comment]
I think this is missing:

```
HTTPResponseException: Package spatialucr/census_cartographic does not exist
```

**Comment by knaaptime** [comment]
doh.

this is a good reminder to catch the exception, though, and let users know they need an internet connection once to grab the data (also [here](https://github.com/spatialucr/osnap/blob/ba7cf56e07b7db61c799be4d63df3a2a9f4d4e5b/osnap/data/data.py#L531))

**Comment by knaaptime** [comment]
this should be resolved now, but going to leave this open until I add an HTTP warning
