### ISSUE TITLE
get san diego & DC data from census with `variables.csv`

### ISSUE THREAD

**Issue by ljwolf** [spatialucr/osnap#3]
# Working notes

1. most of the variables in in the sf3, not the sf1. So, this means the connections are to `cenpy.base.Connection('2000sf3')` and `cenpy.base.Connection('DecennialSF31990')`, not `2000sf1` or `DecennialSF11990`
2. the ACS table column codes are not the SF3 column codes. So, B03001_004E doesn't exist in the sf3. This means we must match by "category," called `concept` in the census API. 
3. sf3 for 2000 from the API only goes down to block groups, not blocks. 

currently, this means building up analogue columns by querying into the pandas dataframe, `connection.variables`:
```python
import cenpy
c2000sf3 = cenpy.base.Connection('2000sf3')
has_ancestry = c2000sf3.variables['concept'].str.lower().apply(lambda x: 'ancestry' in x)
c2000sf3.variables[has_ancestry]['concept'] 
``` 
So, if we can get the column names that correspond, then:
```python
c2000sf3.query(columns=columns, geo_unit='block group', 
               geo_filter=dict(state='06',county='073', tract='*'))
```
should work.

**Comment by knaaptime** [comment]
ltdb give us some of the sf info to match to. I think the geolytics codebook does too but i dont have it on this machine

![image](https://user-images.githubusercontent.com/4213368/46443794-d8ce9480-c723-11e8-9eda-583619d90386.png)

**Comment by knaaptime** [comment]
yep, they're pretty detailed in NCDB too 
![image](https://user-images.githubusercontent.com/4213368/46493387-0cadc680-c7c5-11e8-8a15-52836200567a.png)

so I hope that building out the variable mapper should be straightforward

**Comment by ljwolf** [comment]
can we exchange this manual offline? I need it to get the san diego county data by friday for @sjsrey

**Comment by knaaptime** [comment]
http://www.geolytics.com/pdf/Appendix-E.pdf

**Comment by knaaptime** [comment]
https://s4.ad.brown.edu/projects/diversity/Researcher/LTDB_Codebook.pdf

**Comment by knaaptime** [comment]
the necessary data are now distributed through quilt
