### ISSUE TITLE
example notebook throws import error on clean install

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/osnap#31]
During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ef36febdf931> in <module>
----> 1 import osnap
      2 import libpysal as lps
      3 import geopandas as gpd
      4 import matplotlib.pyplot as plt
      5 import seaborn as sns

~/Dropbox/o/osnap/osnap/__init__.py in <module>
      2 
      3 from . import analytics
----> 4 from . import data
      5 from .data import metros

~/Dropbox/o/osnap/osnap/data/__init__.py in <module>
----> 1 from .data import Dataset, metros, read_ltdb, read_ncdb

~/Dropbox/o/osnap/osnap/data/data.py in <module>
     13     quilt.install("spatialucr/census")
     14     quilt.install("spatialucr/census_cartographic")
---> 15     from quilt.data.knaaptime import census
     16 import matplotlib.pyplot as plt
     17 import pandas as pd

ModuleNotFoundError: No module named 'quilt.data.knaaptime'

**Comment by sjsrey** [comment]
This was on a clean conda environment with a fresh clone of upstream.

**Comment by knaaptime** [comment]
resolved by #32
