### ISSUE TITLE
Anaconda3 in the installation instruction in osnap

### ISSUE THREAD

**Issue by suhanmappingideas** [spatialucr/osnap#46]
I think it is better to mention that "we suggest to use Anaconda3 for osnap since it has been fully tested in Anaconda3".  

Currently the instruction says, "The recommended method for installing OSNAP is with anaconda."  But it does not specify either 2 or 3.

When I tried to install osnpa using yml file you provide in Anaconda2, I had errors and could not resolve errors by myself.

**Comment by knaaptime** [comment]
the [docs](https://os-nap.readthedocs.io/en/latest/installation.html) make clear that osnap is Python 3 only, and once the package is released there will be other methods to install, so the readme will change substantially in the near future to accommodate non-developers
