### ISSUE TITLE
[high priority] mislabelling in osnap.data.dictionary

### ISSUE THREAD

**Issue by suhanmappingideas** [spatialucr/osnap#47]
This is the current
![image](https://user-images.githubusercontent.com/3735841/51220827-bd128700-18eb-11e9-9002-a5bc07d4f8a3.png)

Please correct like below:
![image](https://user-images.githubusercontent.com/3735841/51220938-2abeb300-18ec-11e9-96df-1fac4678f4be.png)

**Comment by knaaptime** [comment]
resolved by 7b89caf

**Comment by suhanmappingideas** [comment]
The rest of the columns should be fixed for 107 and 108. For example, the column ltdb also mislabelled.
