### ISSUE TITLE
LTDB reader: adjust for inflation?

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/osnap#53]
I might be missing sth, but based on [this line](https://github.com/spatialucr/osnap/blob/master/osnap/data/data.py#L184):`inflate_cols = ["mhmval", "mrent", "hinc"]`, I think only these three variables are adjusted for inflation while the other economic variables like per capita income `incpc` are not?

**Comment by knaaptime** [comment]
uh oh, that's right... I thought I'd caught them all but must have missed some.

I was also thinking about moving the adjust inflation and some of the other private functions into a public `util` namespace

--

Elijah Knaap, Ph.D.
Associate Director
Center for Geospatial Sciences
University of California, Riverside
knaaptime.com | @knaaptime

**Comment by weikang9009** [comment]
Yeah, that could be a good option. As long as we have a consistent interface, I am fine either way.
