### ISSUE TITLE
LTDB reader rounding to integers?

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/osnap#54]
[`df = df.round(0)`](https://github.com/spatialucr/osnap/blob/master/osnap/data/data.py#L261)
Can we make this optional? Rounding to integers will lead to a loss of information and sometimes users might need the info for the analysis.

**Comment by knaaptime** [comment]
I'm fine with that. The reason I did this was because when we compute some of the intermediate variables, the results should be an int, and the decimals can lead to a sense of false precision but it would be better to handle that on a case-by-case basis
