### ISSUE TITLE
fix cluster tests

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/osnap#58]
since we're not rounding the ltdb data any more, some of the cluster assignments have changed causing tests to fail

**Comment by weikang9009** [comment]
We might also need to reproduce the relevant parquet files because of the non-rounding and partial inflation adjustment?

**Comment by knaaptime** [comment]
good catch, but i think we're ok on that front. `ltdb.parquet` gets created from the `read_ltdb` function, and travis builds the data from scratch using the raw ltdb files. I will need to regenerate my own ltdb.parquet so i can determine how many clusters will be created on the travis server, but that should be it

**Comment by weikang9009** [comment]
Got it. How about the other `.parquet` files in the data folder? Like [msas.parquet](https://github.com/spatialucr/osnap/blob/master/osnap/data/cbsas.parquet)?

**Comment by knaaptime** [comment]
those are just geoms, but I do need to move them into quilt and out of the repo

**Comment by weikang9009** [comment]
And should we remove the partial inflation adjustment code and ask the users to call the public `util`_adjust_inflation function? OR should we include all the currency variables? Otherwise, we are faced with inconsistency and it will be confusing to users.

**Comment by knaaptime** [comment]
I think we should both expose that function in the public `util` namespace, and include all the currency variables. 

Since we're trying to automate the data preparation for ltdb and ncdb, this should be one of the steps we handle. But when we allow users to include their own data, they may need to adjust currency themselves, so we should make the function available

**Comment by weikang9009** [comment]
Sounds great! I also vote for inflating all the currency variables, but we should make it clear in the docs. Otherwise, users might conduct inflation adjustment again.

**Comment by knaaptime** [comment]
resolved by #65
