### ISSUE TITLE
Reading LTBD data - inconsistent paths for full count and sample files?

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/osnap#61]
Not sure why the relative path of LTDB full count file is different from the sample file?

For instance, [the path to the full count 1980](https://github.com/spatialucr/osnap/blob/master/osnap/data/data.py#L216) is "LTDB_Std_1980_fullcount.csv":
```
    fullcount80 = _ltdb_reader(
        fullcount_zip, "LTDB_Std_1980_fullcount.csv", year=1980)
```
 while [the path for the sample file](https://github.com/spatialucr/osnap/blob/master/osnap/data/data.py#L209) lives in another folder "ltdb_std_all_sample/ltdb_std_1980_sample.csv":
```
    sample80 = _ltdb_reader(
        sample_zip,
        "ltdb_std_all_sample/ltdb_std_1980_sample.csv",
        dropcols=["pop80sf3", "pop80sf4", "hu80sp", "ohu80sp"],
        year=1980,
    )
```

It makes more sense to adopt either form to keep consistency.

**Comment by knaaptime** [comment]
its not us, that is the way the folks at Brown packaged the zip files

**Comment by knaaptime** [comment]
the fullcount files are in the root of the zip, the sampled files are within a folder that sits at the root of the zip, so this is unavoidable
