### ISSUE TITLE
No module named 'libpysal.api' found when I tried to import

### ISSUE THREAD

**Issue by renanxcortes** [spatialucr/osnap#8]
Hello,

When I tried to import the function read_ltdb using the following command:

```
from osnap.data import read_ltdb
```

I got this error:

![image](https://user-images.githubusercontent.com/22593188/47189627-5c76ac80-d2f2-11e8-88c5-0648c0adde9d.png)

In this case I need to manually change this line in 'heuristics.py', but perhaps it would be nice if this intermediate step was not necessary.

Kind regards,
Renan

**Comment by knaaptime** [comment]
this [has been fixed](https://github.com/pysal/region) in region so i think it just needs a new pypi release

**Comment by renanxcortes** [comment]
Ok, thanks! Also, the same thing happened in the 'region/util.py' file. I had to change manually from libpysal.api to libpysal.

**Comment by sjsrey** [comment]
we might be able to fix this with updating osnap's environment.yml file to pull from master for region?

**Comment by knaaptime** [comment]
resolved with 88000b6

**Comment by MyrnaSastre** [comment]
I'm getting the same problem... when trying to "import geosnap", I get:

ModuleNotFoundError: No module named 'libpysal.api'

Before it was requiring the "region" module, so I installed it, and now is this. 

Are you still fixing this manually in the python files?

thanks!!

**Comment by knaaptime** [comment]
that can happen if your `region` gets clobbered by the last released version 

if you're using conda, the easiest fix is to just create a new environment and install osnap from scratch (recommended). If you *need* to keep your current environment try doing `pip uninstall region` until there are no more versions installed, then do `pip install git+git://github.com/pysal/region.git`

that should get you the github version of region that uses pysal2

**Comment by MyrnaSastre** [comment]
It works now. I did what you recommended, uninstalled region and did pip install, but I also installed osnap and geosnap in my current environment.  thanks!
